/* soapStub.h
   Generated by gSOAP 2.8.2 from imgProcess.h
   Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns__ImageData
#define SOAP_TYPE_ns__ImageData (7)
/* ns:ImageData */
class SOAP_CMAC ns__ImageData
{
public:
	int sharedKey;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	int imgHeight;	/* required element of type xsd:int */
	int imgWidth;	/* required element of type xsd:int */
public:
	virtual int soap_type() const { return 7; } /* = unique id SOAP_TYPE_ns__ImageData */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns__ImageData() { ns__ImageData::soap_default(NULL); }
	virtual ~ns__ImageData() { }
};
#endif

#ifndef SOAP_TYPE_ns__Ipl1ChToMat
#define SOAP_TYPE_ns__Ipl1ChToMat (10)
/* ns:Ipl1ChToMat */
struct ns__Ipl1ChToMat
{
public:
	char *InputFilename;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__BinaryThreshold
#define SOAP_TYPE_ns__BinaryThreshold (13)
/* ns:BinaryThreshold */
struct ns__BinaryThreshold
{
public:
	int sharedKey;	/* required element of type xsd:int */
	int imgHeight;	/* required element of type xsd:int */
	int imgWidth;	/* required element of type xsd:int */
	double threshold;	/* required element of type xsd:double */
	double maxValue;	/* required element of type xsd:double */
};
#endif

#ifndef SOAP_TYPE_ns__MorphOpen
#define SOAP_TYPE_ns__MorphOpen (15)
/* ns:MorphOpen */
struct ns__MorphOpen
{
public:
	int sharedKey;	/* required element of type xsd:int */
	int imgHeight;	/* required element of type xsd:int */
	int imgWidth;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__MatToJPGResponse
#define SOAP_TYPE_ns__MatToJPGResponse (18)
/* ns:MatToJPGResponse */
struct ns__MatToJPGResponse
{
public:
	char *OutputFilename;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__MatToJPG
#define SOAP_TYPE_ns__MatToJPG (19)
/* ns:MatToJPG */
struct ns__MatToJPG
{
public:
	int sharedKey;	/* required element of type xsd:int */
	int imgHeight;	/* required element of type xsd:int */
	int imgWidth;	/* required element of type xsd:int */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (20)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (21)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (23)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (26)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (27)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 ns__Ipl1ChToMat(struct soap*, char *InputFilename, ns__ImageData &out);

SOAP_FMAC5 int SOAP_FMAC6 ns__BinaryThreshold(struct soap*, int sharedKey, int imgHeight, int imgWidth, double threshold, double maxValue, ns__ImageData &out);

SOAP_FMAC5 int SOAP_FMAC6 ns__MorphOpen(struct soap*, int sharedKey, int imgHeight, int imgWidth, ns__ImageData &out);

SOAP_FMAC5 int SOAP_FMAC6 ns__MatToJPG(struct soap*, int sharedKey, int imgHeight, int imgWidth, char *&OutputFilename);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__Ipl1ChToMat(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__BinaryThreshold(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__MorphOpen(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__MatToJPG(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__Ipl1ChToMat(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *InputFilename, ns__ImageData &out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__BinaryThreshold(struct soap *soap, const char *soap_endpoint, const char *soap_action, int sharedKey, int imgHeight, int imgWidth, double threshold, double maxValue, ns__ImageData &out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__MorphOpen(struct soap *soap, const char *soap_endpoint, const char *soap_action, int sharedKey, int imgHeight, int imgWidth, ns__ImageData &out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__MatToJPG(struct soap *soap, const char *soap_endpoint, const char *soap_action, int sharedKey, int imgHeight, int imgWidth, char *&OutputFilename);

#endif

/* End of soapStub.h */
