/* soapStub.h
   Generated by gSOAP 2.8.14 from CIA.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20814
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns__RemoveSmallCell
#define SOAP_TYPE_ns__RemoveSmallCell (7)
/* ns:RemoveSmallCell */
class SOAP_CMAC ns__RemoveSmallCell
{
public:
	char *keepedArea;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
	char *biggerArea;	/* optional element of type xsd:string */
public:
	virtual int soap_type() const { return 7; } /* = unique id SOAP_TYPE_ns__RemoveSmallCell */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns__RemoveSmallCell() { ns__RemoveSmallCell::soap_default(NULL); }
	virtual ~ns__RemoveSmallCell() { }
};
#endif

#ifndef SOAP_TYPE_ns__base64Binary
#define SOAP_TYPE_ns__base64Binary (8)
/* Base64 schema type: */
class SOAP_CMAC ns__base64Binary
{
public:
	unsigned char *__ptr;
	int __size;
public:
	virtual int soap_type() const { return 8; } /* = unique id SOAP_TYPE_ns__base64Binary */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns__base64Binary() { ns__base64Binary::soap_default(NULL); }
	virtual ~ns__base64Binary() { }
};
#endif

#ifndef SOAP_TYPE_ns__removeSmallCell
#define SOAP_TYPE_ns__removeSmallCell (14)
/* ns:removeSmallCell */
struct ns__removeSmallCell
{
public:
	char *inputMatFilename;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 14; } /* = unique id SOAP_TYPE_ns__removeSmallCell */
};
#endif

#ifndef SOAP_TYPE_ns__scanningCellResponse
#define SOAP_TYPE_ns__scanningCellResponse (17)
/* ns:scanningCellResponse */
struct ns__scanningCellResponse
{
public:
	char **OutputMatFilename;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
public:
	int soap_type() const { return 17; } /* = unique id SOAP_TYPE_ns__scanningCellResponse */
};
#endif

#ifndef SOAP_TYPE_ns__scanningCell
#define SOAP_TYPE_ns__scanningCell (18)
/* ns:scanningCell */
struct ns__scanningCell
{
public:
	char *biggerArea;	/* optional element of type xsd:string */
	char *keepArea;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 18; } /* = unique id SOAP_TYPE_ns__scanningCell */
};
#endif

#ifndef SOAP_TYPE_ns__trainANNResponse
#define SOAP_TYPE_ns__trainANNResponse (20)
/* ns:trainANNResponse */
struct ns__trainANNResponse
{
public:
	char **OutputMatFilename;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
public:
	int soap_type() const { return 20; } /* = unique id SOAP_TYPE_ns__trainANNResponse */
};
#endif

#ifndef SOAP_TYPE_ns__trainANN
#define SOAP_TYPE_ns__trainANN (21)
/* ns:trainANN */
struct ns__trainANN
{
public:
	char *inputMatFilename;	/* optional element of type xsd:string */
	char *neuralFile;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 21; } /* = unique id SOAP_TYPE_ns__trainANN */
};
#endif

#ifndef SOAP_TYPE_ns__separateCellResponse
#define SOAP_TYPE_ns__separateCellResponse (23)
/* ns:separateCellResponse */
struct ns__separateCellResponse
{
public:
	char **OutputMatFilename;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
public:
	int soap_type() const { return 23; } /* = unique id SOAP_TYPE_ns__separateCellResponse */
};
#endif

#ifndef SOAP_TYPE_ns__separateCell
#define SOAP_TYPE_ns__separateCell (24)
/* ns:separateCell */
struct ns__separateCell
{
public:
	char *input1;	/* optional element of type xsd:string */
	char *input2;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 24; } /* = unique id SOAP_TYPE_ns__separateCell */
};
#endif

#ifndef SOAP_TYPE_ns__prepareResultResponse
#define SOAP_TYPE_ns__prepareResultResponse (26)
/* ns:prepareResultResponse */
struct ns__prepareResultResponse
{
public:
	char **OutputMatFilename;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
public:
	int soap_type() const { return 26; } /* = unique id SOAP_TYPE_ns__prepareResultResponse */
};
#endif

#ifndef SOAP_TYPE_ns__prepareResult
#define SOAP_TYPE_ns__prepareResult (27)
/* ns:prepareResult */
struct ns__prepareResult
{
public:
	char *inputMatFilename;	/* optional element of type xsd:string */
	char *afterthresNN;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 27; } /* = unique id SOAP_TYPE_ns__prepareResult */
};
#endif

#ifndef SOAP_TYPE_ns__viewImageResponse
#define SOAP_TYPE_ns__viewImageResponse (30)
/* ns:viewImageResponse */
struct ns__viewImageResponse
{
public:
	ns__base64Binary image;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns:base64Binary */
public:
	int soap_type() const { return 30; } /* = unique id SOAP_TYPE_ns__viewImageResponse */
};
#endif

#ifndef SOAP_TYPE_ns__viewImage
#define SOAP_TYPE_ns__viewImage (31)
/* ns:viewImage */
struct ns__viewImage
{
public:
	char *inputMatFilename;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 31; } /* = unique id SOAP_TYPE_ns__viewImage */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (32)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	int soap_type() const { return 32; } /* = unique id SOAP_TYPE_SOAP_ENV__Header */
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (33)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
public:
	int soap_type() const { return 33; } /* = unique id SOAP_TYPE_SOAP_ENV__Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (35)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
public:
	int soap_type() const { return 35; } /* = unique id SOAP_TYPE_SOAP_ENV__Detail */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (38)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 38; } /* = unique id SOAP_TYPE_SOAP_ENV__Reason */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (39)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
public:
	int soap_type() const { return 39; } /* = unique id SOAP_TYPE_SOAP_ENV__Fault */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 ns__removeSmallCell(struct soap*, char *inputMatFilename, ns__RemoveSmallCell &out);

SOAP_FMAC5 int SOAP_FMAC6 ns__scanningCell(struct soap*, char *biggerArea, char *keepArea, char **OutputMatFilename);

SOAP_FMAC5 int SOAP_FMAC6 ns__trainANN(struct soap*, char *inputMatFilename, char *neuralFile, char **OutputMatFilename);

SOAP_FMAC5 int SOAP_FMAC6 ns__separateCell(struct soap*, char *input1, char *input2, char **OutputMatFilename);

SOAP_FMAC5 int SOAP_FMAC6 ns__prepareResult(struct soap*, char *inputMatFilename, char *afterthresNN, char **OutputMatFilename);

SOAP_FMAC5 int SOAP_FMAC6 ns__viewImage(struct soap*, char *inputMatFilename, ns__base64Binary &image);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__removeSmallCell(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__scanningCell(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__trainANN(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__separateCell(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__prepareResult(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__viewImage(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__removeSmallCell(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *inputMatFilename, ns__RemoveSmallCell &out);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__scanningCell(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *biggerArea, char *keepArea, char **OutputMatFilename);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__trainANN(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *inputMatFilename, char *neuralFile, char **OutputMatFilename);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__separateCell(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *input1, char *input2, char **OutputMatFilename);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__prepareResult(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *inputMatFilename, char *afterthresNN, char **OutputMatFilename);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__viewImage(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *inputMatFilename, ns__base64Binary &image);

#endif

/* End of soapStub.h */
