#!/bin/bash
#g++ -o standAloneServer `pkg-config opencv --cflags` `pkg-config opencv --libs` -fopenmp standAloneServer.cpp soapC.cpp soapServer.cpp stdsoap2.cpp
g++ -o standAloneServer standAloneServer.cpp soapC.cpp soapServer.cpp stdsoap2.cpp  `pkg-config opencv --cflags` `pkg-config opencv --libs` -fopenmp

echo "***compiled***"
#sudo chmod a+x maliServer
#echo "***gived a+x***"
#sudo cp maliServer /var/www/cgi-bin/
#echo "***copied maliServer***"
sudo cp standAlone.wsdl /var/www/
echo "***copied mali.wsdl***"

#g++ cv_example.cpp -o cvex `pkg-config opencv --cflags` `pkg-config opencv --libs`
