#!/bin/bash
g++ `pkg-config opencv --cflags` -fopenmp -DDEBUG -o imgProcessServer imgProcessServer.cpp soapC.cpp soapServer.cpp stdsoap2.cpp `pkg-config opencv --libs`
#g++ `pkg-config opencv --cflags` -fopenmp -o maliServer maliServer.cpp soapC.cpp soapServer.cpp stdsoap2.cpp `pkg-config opencv --libs`
#g++ `pkg-config opencv --cflags` `pkg-config opencv --libs` -o maliServer maliServer.cpp soapC.cpp soapServer.cpp stdsoap2.cpp
echo "***compiled***"
sudo chmod a+x imgProcessServer
echo "***gived a+x***"
sudo cp imgProcessServer /var/www/cgi-bin/
echo "***copied maliServer***"
sudo cp imgProcess.wsdl /var/www/
echo "***copied mali.wsdl***"
