#!/bin/bash
#g++ -I/usr/include/opencv -lcxcore -lhighgui -lm -o maliServer maliServer.cpp soapC.cpp soapServer.cpp stdsoap2.cpp
#g++ `pkg-config opencv --cflags` `pkg-config opencv --libs`  -o maliServer maliServer.cpp soapC.cpp soapServer.cpp stdsoap2.cpp
g++ -I/usr/include/opencv maliServer.cpp soapC.cpp soapServer.cpp stdsoap2.cpp `pkg-config opencv --libs` -fopenmp -o maliServer 
echo "***compiled***"
sudo chmod a+x maliServer
echo "***gived a+x***"
sudo cp maliServer /var/www/cgi-bin/
echo "***copied maliServer***"
sudo cp mali.wsdl /var/www/
echo "***copied mali.wsdl***"
