#!/bin/bash
g++ -o calcserver calcserver.cpp stdsoap2.cpp soapC.cpp soapServer.cpp
echo "***compiled***"
sudo chmod a+x calcserver
echo "***gived a+x***"
sudo cp calcserver /var/www/cgi-bin/
echo "***copied imgProcessServer***"
sudo cp calc.wsdl /var/www/
echo "***copied imgProcess.wsdl***"
